on: [push]

name: Build Docker Image And Submit Metadata To ReARM Demo

jobs:
  build-backend:
    name: Build And Push Backend
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: ReARM Build And Submit Backend Release metadata action
        uses: relizaio/rearm-docker-action@2025-05-sign-attest
        with:
          registry_username: ${{ secrets.DOCKER_LOGIN }}
          registry_password: ${{ secrets.DOCKER_TOKEN }}
          registry_host: registry.test.relizahub.com
          image_namespace: registry.test.relizahub.com/c8ff04b4-eb2d-4033-8a1d-9fb8d1ff31c8-public
          image_name: rebom-backend
          rearm_api_id: ${{ secrets.REARM_REBOM_BACKEND_API_ID }}
          rearm_api_key: ${{ secrets.REARM_REBOM_BACKEND_API_KEY }}
          rearm_api_url: https://dev.rearmhq.com
          path: backend
          enable_sbom: 'true'
          source_code_sbom_type: 'npm'
