on: [push]

name: Build Docker Image And Submit Metadata To ReARM Demo

jobs:
  build-backend:
    name: Build And Push Backend
    runs-on: ubuntu-latest
    steps:
      - name: ReARM Build And Submit Backend Release metadata action
        uses: relizaio/rearm-docker-action@main
        with:
          registry_username: ${{ secrets.DOCKER_LOGIN }}
          registry_password: ${{ secrets.DOCKER_TOKEN }}
          registry_host: registry.relizahub.com
          image_namespace: registry.relizahub.com/d50bca61-d588-44ee-9dae-c0fbcd376270-public
          image_name: rebom-backend
          rearm_api_id: ${{ secrets.REARM_REBOM_BACKEND_API_ID }}
          rearm_api_key: ${{ secrets.REARM_REBOM_BACKEND_API_KEY }}
          rearm_api_url: https://demo.rearmhq.com
          path: backend
          enable_sbom: 'true'
          source_code_sbom_type: 'npm'
